In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('Absenteeism preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month value  Day of the week  \
0     False     False     False      True          289               36   
1     False     False     False     False          118               13   
2     False     False     False      True          179               51   
3      True     False     False     False          279                5   
4     False     False     False      True          289               36   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                      33           239.554   30                        1   
1                      50           239.554   31                        1   
2                      38           239.554   31                        1   
3                      39           239.554   24                        1   
4                      33           239.554   30                        1   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0                2          0         4     7                          1  
1                1          0         0     7                          1  
2                0          0         2     7                          2  
3                2          0         4     7                          3  
4                2          0         2     7                          3

## Create the targets

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

2.0

if a person is absent for less then 2 hours then we will assign the value 0 (moderately absent) otherwise 1 (excessively absent)

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [6]:
targets

array([0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month value  Day of the week  \
0       False     False     False      True          289               36   
1       False     False     False     False          118               13   
2       False     False     False      True          179               51   
3        True     False     False     False          279                5   
4       False     False     False      True          289               36   
..        ...       ...       ...       ...          ...              ...   
695      True     False     False     False          179               22   
696      True     False     False     False          225               26   
697      True     False     False     False          330               16   
698     False     False     False      True          235               16   
699     False     False     False      True          291               31   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                        33           239.554   30                        1   
1                        50           239.554   31                        1   
2                        38           239.554   31                        1   
3                        39           239.554   24                        1   
4                        33           239.554   30                        1   
..                      ...               ...  ...                      ...   
695                      40           237.656   22                        2   
696                      28           237.656   24                        1   
697                      28           237.656   25                        2   
698                      32           237.656   25                        3   
699                      40           237.656   25                        1   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0                  2          0         4     7                          1   
1                  1          0         0     7                          1   
2                  0          0         2     7                          2   
3                  2          0         4     7                          3   
4                  2          0         2     7                          3   
..               ...        ...       ...   ...                        ...   
695                2          0         8     5                          2   
696                1          1         3     5                          2   
697                0          0         8     5                          3   
698                0          0         2     5                          3   
699                1          0         2     5                          3   

     Excessive Absenteeism  
0                        0  
1                        0  
2                        0  
3                        1  
4                        1  
..                     ...  
695                      0  
696                      0  
697                      1  
698                      1  
699                      1  

[700 rows x 16 columns]

In [9]:
targets.sum() / targets.shape[0]

0.37714285714285717

In [10]:
data_preprocessed['Absenteeism Time in Hours'].unique()

array([1, 2, 3, 4, 0, 6, 5], dtype=int64)

In [11]:
data_preprocessed['Absenteeism Time in Hours'].value_counts()

Absenteeism Time in Hours
2    154
1    141
0    141
4    132
3    119
6      9
5      4
Name: count, dtype: int64

In [12]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis =1)

In [13]:
data_with_targets

Reason_1  Reason_2  Reason_3  Reason_4  Month value  Day of the week  \
0       False     False     False      True          289               36   
1       False     False     False     False          118               13   
2       False     False     False      True          179               51   
3        True     False     False     False          279                5   
4       False     False     False      True          289               36   
..        ...       ...       ...       ...          ...              ...   
695      True     False     False     False          179               22   
696      True     False     False     False          225               26   
697      True     False     False     False          330               16   
698     False     False     False      True          235               16   
699     False     False     False      True          291               31   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                        33           239.554   30                        1   
1                        50           239.554   31                        1   
2                        38           239.554   31                        1   
3                        39           239.554   24                        1   
4                        33           239.554   30                        1   
..                      ...               ...  ...                      ...   
695                      40           237.656   22                        2   
696                      28           237.656   24                        1   
697                      28           237.656   25                        2   
698                      32           237.656   25                        3   
699                      40           237.656   25                        1   

     Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0                  2          0         4     7                      0  
1                  1          0         0     7                      0  
2                  0          0         2     7                      0  
3                  2          0         4     7                      1  
4                  2          0         2     7                      1  
..               ...        ...       ...   ...                    ...  
695                2          0         8     5                      0  
696                1          1         3     5                      0  
697                0          0         8     5                      1  
698                0          0         2     5                      1  
699                1          0         2     5                      1  

[700 rows x 15 columns]

In [14]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [15]:
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month value  Day of the week  \
0       False     False     False      True          289               36   
1       False     False     False     False          118               13   
2       False     False     False      True          179               51   
3        True     False     False     False          279                5   
4       False     False     False      True          289               36   
..        ...       ...       ...       ...          ...              ...   
695      True     False     False     False          179               22   
696      True     False     False     False          225               26   
697      True     False     False     False          330               16   
698     False     False     False      True          235               16   
699     False     False     False      True          291               31   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                        33           239.554   30                        1   
1                        50           239.554   31                        1   
2                        38           239.554   31                        1   
3                        39           239.554   24                        1   
4                        33           239.554   30                        1   
..                      ...               ...  ...                      ...   
695                      40           237.656   22                        2   
696                      28           237.656   24                        1   
697                      28           237.656   25                        2   
698                      32           237.656   25                        3   
699                      40           237.656   25                        1   

     Body Mass Index  Education  Children  Pets  
0                  2          0         4     7  
1                  1          0         0     7  
2                  0          0         2     7  
3                  2          0         4     7  
4                  2          0         2     7  
..               ...        ...       ...   ...  
695                2          0         8     5  
696                1          1         3     5  
697                0          0         8     5  
698                0          0         2     5  
699                1          0         2     5  

[700 rows x 14 columns]

In [16]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month value',
       'Day of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [17]:
columns_to_scale = ['Month value', 'Day of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index',
       'Children', 'Pets']

In [18]:
columns_not_scale = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [19]:
df_scaled = unscaled_inputs[columns_to_scale]
df_not_scaled = unscaled_inputs[columns_not_scale]

In [20]:
from sklearn.preprocessing import StandardScaler

In [21]:
absenteesim_scaler = StandardScaler()

absenteesim_scaler.fit(df_scaled)

scaled_inputs=absenteesim_scaler.transform(df_scaled)

In [22]:
df_scaled = pd.DataFrame(scaled_inputs, columns=columns_to_scale)
scaled_inputs = pd.concat([df_scaled, df_not_scaled], axis=1)
scaled_inputs

Month value  Day of the week  Transportation Expense  Distance to Work  \
0       1.005844         0.412816               -0.536062         -0.806331   
1      -1.574681        -1.141882                2.130803         -0.806331   
2      -0.654143         1.426749                0.248310         -0.806331   
3       0.854936        -1.682647                0.405184         -0.806331   
4       1.005844         0.412816               -0.536062         -0.806331   
..           ...              ...                     ...               ...   
695    -0.654143        -0.533522                0.562059         -0.853789   
696     0.040034        -0.263140               -1.320435         -0.853789   
697     1.624567        -0.939096               -1.320435         -0.853789   
698     0.190942        -0.939096               -0.692937         -0.853789   
699     1.036026         0.074838                0.562059         -0.853789   

          Age  Daily Work Load Average  Body Mass Index  Children      Pets  \
0    0.767431                -0.423685         0.880469 -0.218105  0.182726   
1    1.002633                -0.423685        -0.019280 -0.534035  0.182726   
2    1.002633                -0.423685        -0.919030 -0.376070  0.182726   
3   -0.643782                -0.423685         0.880469 -0.218105  0.182726   
4    0.767431                -0.423685         0.880469 -0.376070  0.182726   
..        ...                      ...              ...       ...       ...   
695 -1.114186                 1.074191         0.880469  0.097825 -0.388293   
696 -0.643782                -0.423685        -0.019280 -0.297087 -0.388293   
697 -0.408580                 1.074191        -0.919030  0.097825 -0.388293   
698 -0.408580                 2.572066        -0.919030 -0.376070 -0.388293   
699 -0.408580                -0.423685        -0.019280 -0.376070 -0.388293   

     Reason_1  Reason_2  Reason_3  Reason_4  Education  
0       False     False     False      True          0  
1       False     False     False     False          0  
2       False     False     False      True          0  
3        True     False     False     False          0  
4       False     False     False      True          0  
..        ...       ...       ...       ...        ...  
695      True     False     False     False          0  
696      True     False     False     False          1  
697      True     False     False     False          0  
698     False     False     False      True          0  
699     False     False     False      True          0  

[700 rows x 14 columns]

In [23]:
scaled_inputs.shape

(700, 14)

In [24]:
reordered_columns = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month value',
       'Day of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets']

In [25]:
scaled_inputs = scaled_inputs[reordered_columns]

In [26]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month value  Day of the week  \
0       False     False     False      True     1.005844         0.412816   
1       False     False     False     False    -1.574681        -1.141882   
2       False     False     False      True    -0.654143         1.426749   
3        True     False     False     False     0.854936        -1.682647   
4       False     False     False      True     1.005844         0.412816   
..        ...       ...       ...       ...          ...              ...   
695      True     False     False     False    -0.654143        -0.533522   
696      True     False     False     False     0.040034        -0.263140   
697      True     False     False     False     1.624567        -0.939096   
698     False     False     False      True     0.190942        -0.939096   
699     False     False     False      True     1.036026         0.074838   

     Transportation Expense  Distance to Work       Age  \
0                 -0.536062         -0.806331  0.767431   
1                  2.130803         -0.806331  1.002633   
2                  0.248310         -0.806331  1.002633   
3                  0.405184         -0.806331 -0.643782   
4                 -0.536062         -0.806331  0.767431   
..                      ...               ...       ...   
695                0.562059         -0.853789 -1.114186   
696               -1.320435         -0.853789 -0.643782   
697               -1.320435         -0.853789 -0.408580   
698               -0.692937         -0.853789 -0.408580   
699                0.562059         -0.853789 -0.408580   

     Daily Work Load Average  Body Mass Index  Education  Children      Pets  
0                  -0.423685         0.880469          0 -0.218105  0.182726  
1                  -0.423685        -0.019280          0 -0.534035  0.182726  
2                  -0.423685        -0.919030          0 -0.376070  0.182726  
3                  -0.423685         0.880469          0 -0.218105  0.182726  
4                  -0.423685         0.880469          0 -0.376070  0.182726  
..                       ...              ...        ...       ...       ...  
695                 1.074191         0.880469          0  0.097825 -0.388293  
696                -0.423685        -0.019280          1 -0.297087 -0.388293  
697                 1.074191        -0.919030          0  0.097825 -0.388293  
698                 2.572066        -0.919030          0 -0.376070 -0.388293  
699                -0.423685        -0.019280          0 -0.376070 -0.388293  

[700 rows x 14 columns]

## Spliting the data into test and train

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state=20)

In [29]:
print(x_train.shape, y_train.shape)

(560, 14) (560,)


In [30]:
print(x_test.shape, y_test.shape)

(140, 14) (140,)


### Logistic regression

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [32]:
reg2 = LogisticRegression()

In [33]:
reg2.fit(x_train, y_train)

LogisticRegression()

In [34]:
reg2.score(x_train, y_train)

0.6535714285714286

### Manually check the accuracy

In [35]:
model_output = reg2.predict(x_train)
model_output

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,

In [36]:
y_train

array([1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,

In [37]:
model_output == y_train

array([False, False, False,  True,  True, False, False, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False, False,  True,  True,  True,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True, False, False,  True, False,  True,  True, False,  True,
        True,  True, False, False,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True, False,  True, False, False, False,  True,  True, False,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,

In [38]:
np.sum(model_output==y_train)/model_output.shape[0]

0.6535714285714286

#### Finding the intercept and coeff

In [39]:
reg2.intercept_

array([-0.61771953])

In [40]:
reg2.coef_

array([[-0.109851  , -0.43129312, -0.4479662 ,  0.23101627, -0.01891127,
         0.37242007,  0.21627643,  0.06376567, -0.23606155,  0.32757915,
         0.25214423, -0.16183475, -0.22688046,  0.19749574]])

In [41]:
feature_names = unscaled_inputs.columns.values

In [42]:
feature_names

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month value',
       'Day of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [43]:
summary_table = pd.DataFrame(columns=['Feature names'], data=feature_names)
summary_table['Coefficient'] = np.transpose(reg2.coef_)
summary_table

Feature names  Coefficient
0                  Reason_1    -0.109851
1                  Reason_2    -0.431293
2                  Reason_3    -0.447966
3                  Reason_4     0.231016
4               Month value    -0.018911
5           Day of the week     0.372420
6    Transportation Expense     0.216276
7          Distance to Work     0.063766
8                       Age    -0.236062
9   Daily Work Load Average     0.327579
10          Body Mass Index     0.252144
11                Education    -0.161835
12                 Children    -0.226880
13                     Pets     0.197496

In [44]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg2.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature names  Coefficient
0                 Intercept    -0.617720
1                  Reason_1    -0.109851
2                  Reason_2    -0.431293
3                  Reason_3    -0.447966
4                  Reason_4     0.231016
5               Month value    -0.018911
6           Day of the week     0.372420
7    Transportation Expense     0.216276
8          Distance to Work     0.063766
9                       Age    -0.236062
10  Daily Work Load Average     0.327579
11          Body Mass Index     0.252144
12                Education    -0.161835
13                 Children    -0.226880
14                     Pets     0.197496

In [45]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [46]:
summary_table

Feature names  Coefficient  Odds_ratio
0                 Intercept    -0.617720    0.539173
1                  Reason_1    -0.109851    0.895968
2                  Reason_2    -0.431293    0.649668
3                  Reason_3    -0.447966    0.638926
4                  Reason_4     0.231016    1.259880
5               Month value    -0.018911    0.981266
6           Day of the week     0.372420    1.451242
7    Transportation Expense     0.216276    1.241446
8          Distance to Work     0.063766    1.065843
9                       Age    -0.236062    0.789732
10  Daily Work Load Average     0.327579    1.387605
11          Body Mass Index     0.252144    1.286782
12                Education    -0.161835    0.850582
13                 Children    -0.226880    0.797016
14                     Pets     0.197496    1.218348

In [47]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature names  Coefficient  Odds_ratio
6           Day of the week     0.372420    1.451242
10  Daily Work Load Average     0.327579    1.387605
11          Body Mass Index     0.252144    1.286782
4                  Reason_4     0.231016    1.259880
7    Transportation Expense     0.216276    1.241446
14                     Pets     0.197496    1.218348
8          Distance to Work     0.063766    1.065843
5               Month value    -0.018911    0.981266
1                  Reason_1    -0.109851    0.895968
12                Education    -0.161835    0.850582
13                 Children    -0.226880    0.797016
9                       Age    -0.236062    0.789732
2                  Reason_2    -0.431293    0.649668
3                  Reason_3    -0.447966    0.638926
0                 Intercept    -0.617720    0.539173

From the summary table we can see the distance to work variable is very insignificant as the coeff value is close to zero and odds ratio is close to 1 so we can safely ommit the variable or just keep it as it has no significant impact on the model

## Testing the model

In [48]:
reg2.score(x_test, y_test)

0.5714285714285714

Test accuracy score achived 57%

In [49]:
predicted_proba = reg2.predict_proba(x_test)
predicted_proba

array([[0.50920808, 0.49079192],
       [0.51748834, 0.48251166],
       [0.71627579, 0.28372421],
       [0.6451138 , 0.3548862 ],
       [0.3868372 , 0.6131628 ],
       [0.72240374, 0.27759626],
       [0.7060261 , 0.2939739 ],
       [0.77592228, 0.22407772],
       [0.74702409, 0.25297591],
       [0.58960323, 0.41039677],
       [0.59019188, 0.40980812],
       [0.66052164, 0.33947836],
       [0.68313978, 0.31686022],
       [0.59615202, 0.40384798],
       [0.62920007, 0.37079993],
       [0.7253936 , 0.2746064 ],
       [0.63734022, 0.36265978],
       [0.59954179, 0.40045821],
       [0.90071141, 0.09928859],
       [0.71199689, 0.28800311],
       [0.63191408, 0.36808592],
       [0.6451138 , 0.3548862 ],
       [0.79583987, 0.20416013],
       [0.78089599, 0.21910401],
       [0.85808588, 0.14191412],
       [0.66617206, 0.33382794],
       [0.65734393, 0.34265607],
       [0.38674707, 0.61325293],
       [0.67168566, 0.32831434],
       [0.6451138 , 0.3548862 ],
       [0.

In [50]:
predicted_proba[:,1]

array([0.49079192, 0.48251166, 0.28372421, 0.3548862 , 0.6131628 ,
       0.27759626, 0.2939739 , 0.22407772, 0.25297591, 0.41039677,
       0.40980812, 0.33947836, 0.31686022, 0.40384798, 0.37079993,
       0.2746064 , 0.36265978, 0.40045821, 0.09928859, 0.28800311,
       0.36808592, 0.3548862 , 0.20416013, 0.21910401, 0.14191412,
       0.33382794, 0.34265607, 0.61325293, 0.32831434, 0.3548862 ,
       0.38760522, 0.20372855, 0.36817401, 0.43999024, 0.3548862 ,
       0.33518445, 0.24693277, 0.15909024, 0.37698469, 0.70540533,
       0.36145672, 0.40329343, 0.29210808, 0.68370415, 0.35865723,
       0.09859684, 0.16265708, 0.50586818, 0.338047  , 0.36659398,
       0.54386378, 0.33964903, 0.24567877, 0.42847527, 0.26959297,
       0.52006676, 0.19075095, 0.27957169, 0.24782327, 0.24966022,
       0.33696877, 0.26552792, 0.37704863, 0.19222431, 0.32811314,
       0.44310564, 0.32839471, 0.26192342, 0.16772093, 0.45720124,
       0.25847402, 0.35838024, 0.21651006, 0.4672862 , 0.39396

## Save the model

In [51]:
import pickle

In [52]:
with open('model', 'wb') as file:
    pickle.dump(reg2, file)

In [54]:
with open('Scalar', 'wb') as file:
    pickle.dump(absenteesim_scaler, file)